name = "shindora-cloudflare"
main = "cloudflare-worker.js"
compatibility_date = "2026-01-01"

[vars]
ORIGIN_APP_URL = "https://e127797a-9d93-4499-be31-b84492eb6a96.preview.emergentagent.com"

# Cron Trigger 24 Jam untuk Auto Refresh Token Expired
[triggers]
crons = ["0 0 * * *"]
